### ISSUE TITLE
undo place of the bomberman part

### ISSUE THREAD

**Issue by themarwik** [mdsimmo/Bomberman#15]
**What problem does the feature solve**
no undo when the bomberman building is placed wrong place

**Describe the solution you'd like**
undo place of the bomberman part when it is placed fail

**Describe alternatives you've considered**

**Additional context**

**Comment by mdsimmo** [comment]
Should be able to add support for WorldEdit history, so `//undo` will work properly.

**Comment by mdsimmo** [comment]
Implemented in v0.6.3. Use `\bm undo`
