### ISSUE TITLE
worldguard support

### ISSUE THREAD

**Issue by themarwik** [mdsimmo/Bomberman#16]
**What problem does the feature solve**
A clear and concise description of what the problem is. Ex. "It is difficult for players to ..."

**Describe the solution you'd like**
one idea is to have support for worldguard / worldguard flags so default players can get access/permission to use the plugin in a spawn area that is used worldguard on the place. when it is in a worldguard area no one can place tnt on it as it using in the game

**Describe alternatives you've considered**
If any, a clear and concise description of any alternative solutions or features you've considered.

**Additional context**

**Comment by mdsimmo** [comment]
Will look into best method of implementing...

**Comment by mdsimmo** [comment]
Let me present you with four options:
1. Add a region inside the outer region with higher priority. Disable all restrictions on the inner region.
2. Latest update (0.6.2) gives all bomberman players the "group.bomberman" permission. Use this to disable flags on the region
3. All bomberman players have the scoreboard tag "bm_player" attached. Use command blocks to select nearby players and run arbitrary commands (e.g give permissions.)
4. Wait for Issue #18 to be implemented and hook into the on-player-join/on-player-leave events (might be a while before I implement that though)

**Comment by themarwik** [comment]
thanks for the information. just thinked that whould have helped for other users to, to have it in a spawn place so the users not can destroy the buildings and can place the tnt block in the game
