### ISSUE TITLE
You should not be using reflection to add player permission attachments

### ISSUE THREAD

**Issue by JorelAli** [mdsimmo/bomberman#27]
**What code needs changing**
In `io.github.mdsimmo.bomberman.game.GamePlayer.kt`, you have the following code which adds a permission attachment to a player:

```kotlin
// Add a permission group for WorldGuard compatibility (must be done before teleporting)
// Wrap in try loop because it is quite dodgy how other plugins implement
try {
    val playerPermissions = BukkitUtils.getPermissibleBase(player)
    playerPermissions?.addAttachment(plugin, "group.bomberman", true)
} catch (e: Exception) {
    plugin.logger.log(Level.WARNING, "Unable to add permissions", e)
}
```

This calls `io.github.mdsimmo.bomberman.utils.BukkitUtils.kt`'s `getPermissibleBase()` function which calls `HUMAN_ENTITY_PERMISSIBLE_FIELD` which uses reflection. This does not abide by normal plugin coding standards (plugins should not be accessing OBC!), and thus breaks an interaction with one of the plugin APIs that I am maintaining.

**What solution would you like**
The `Player` object inherits from `Permissible` (as shown [here](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html) at the top under "All Superinterfaces"), meaning you can simply use the following:

```kotlin
player.addAttachment(plugin, "group.bomberman", true)
```

This avoids the need of:
- Using reflection to access `perm` from `CraftHumanEntity`
- Accessing the OBC class `CraftHumanEntity` directly
- Modifying the `perm`'s access modifiers to be accessible, which is a Java security issue

Thanks in advance!

**Comment by mdsimmo** [comment]
Oh, that's how it's meant to be done!

 I thought it was strange spigot had a built-in permission handler, but no way to access it. Kinda obvious now in hindsight.

Will fix and add to next release.

**Comment by mdsimmo** [comment]
Added to v0.7.0
