### ISSUE TITLE
Permission problem

### ISSUE THREAD

**Issue by scorninpc** [mdsimmo/Bomberman#3]
I'm trying to get this great event on my server, but on tests, with GroupManager, with bomberman.* and all perms, i still getting no permission

If i remove all, and run only with this plugin and worldedit, i still getting the error

![image](https://user-images.githubusercontent.com/2607849/80292923-04afd180-8731-11ea-97e9-7ffa2db82b3e.png)

No error on console

![image](https://user-images.githubusercontent.com/2607849/80292928-109b9380-8731-11ea-82c6-2c44f1d867f9.png)

Can you help me?

**Comment by scorninpc** [comment]
works only with OP. But players cannot join without OP too

**Comment by scorninpc** [comment]
I'v solved with 4.10. Only on spigot site, bukkit are 4.7 =/ Thank you for this NIIIICE game =D

**Comment by mdsimmo** [comment]
Glad you figured it out.

The permission bug was fixed in v0.4.8. I've uploaded it to Bukkit, but it takes a few days for Bukkit to approve the files.
