### ISSUE TITLE
Start Game Issue

### ISSUE THREAD

**Issue by cleveravi** [mdsimmo/Bomberman#6]
When I start the Bomberman game the glass that surrounds the player to make sure he can't do anything till the game starts (which usually disappears when it does start) is not disappearing. I've tried going into the configs, everything. I have the spawn points set using the sign and it's a custom schematic but the glass won't disappear.
Please help.

**Comment by mdsimmo** [comment]
Issue closed as problem was due to placing the white stained glass in the schematic.
